### ISSUE TITLE
Hashes are not imported

### ISSUE THREAD

**Issue by mo3g666** [LeonardSSH/ragemp-typescript#2]
Hello, when packing the project, there is no transfer of hashes from the npm package

index.ts
```ts
import './setup';

mp.events.add('playerReady', (player) => {
	player.model = RageEnums.Hashes.Ped.U_F_M_CORPSE_01;
});
```

index.js

```js
'use strict';

var path = require('path');
var dotenv = require('dotenv');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var path__default = /*#__PURE__*/_interopDefaultLegacy(path);

dotenv.config({
    path: path__default["default"].resolve('.env')
});

mp.events.add('playerReady', function(player) {
    player.model = RageEnums.Hashes.Ped.U_F_M_CORPSE_01;
});
```

**Comment by leonardssh** [comment]
In order to benefit from [const enums](https://www.typescriptlang.org/docs/handbook/enums.html#const-enums), you must replace the SWC compiler with [rollup-plugin-typescript2](https://www.npmjs.com/package/rollup-plugin-typescript2) or [@rollup/plugin-typescript](https://www.npmjs.com/package/@rollup/plugin-typescript)

Because SWC does not yet have support for const enums.

**Comment by leonardssh** [comment]
You can revert https://github.com/LeonardSSH/ragemp-typescript/commit/7a53b7459fdc88f135a9bdf0643e7719028ff05a and the compiler is already set up.
